#TUPLAS
#-NO SON MODIFICABLES
#CREAR Y MOSTRAR TUPLAS
a=()
print(a)
a=("Priss","Petra","Snow","Priss")
print(a)
#MOSTRAR UN ELEMNTO DE LA TUPLA
print(a[1])
#MOIDICAR ELEMENTOS DE UNA TUPLA
#a[0]="MyQueen"

#FUNCIONES
print(a.count("Priss"))#CONTAR CUANTAS VECES SE REPITE
print(len(a))#CONTAR CUANTOS ELEMENTOS TIENE LA TUPLA
print(a.index("Snow"))#REGRESA LA POSICION DEL ELEMENTO QUE PASAMOS COMO PARAMETRO